In [67]:
import numpy as np
# The Basics

In [68]:
a = np.array([1, 2, 3], dtype = 'int32')
print(a)

[1 2 3]


In [69]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [70]:
#Get dimension
a.ndim

1

In [71]:
#get Shape
b.shape


(2, 3)

In [72]:
#Get type
a.dtype

dtype('int32')

In [73]:
#get size
a.itemsize
b.itemsize

8

In [74]:
#Get total size
a.nbytes

12

In [75]:
#Accessing/Changing specific elements, rows, columns, etc

In [77]:
a = np.array([[1, 2, 3, 4, 5, 6,7 ],[8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [78]:
#Get a specific element[r, c]
a[1, 5]

13

In [79]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [80]:
# get a specific column
a[:, 2]

array([ 3, 10])

In [81]:
#getting little more fency[startindex : endindex:stepsize]
a[0, 1:6:2]
a[0, 1:-1:2]

array([2, 4, 6])

In [82]:
a[1, 5] = 20
print(a)

a[:, 2] = [1, 2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [83]:
#3d example
b = np.array([[[1,2],[3, 4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [84]:
#Get specific element(work outside in)
b[0,1,1]
b[0, 1, :
 ]

array([3, 4])

In [85]:
#replace 
b[:, 1, :] = [[9, 9], [8, 8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [86]:
#Initialize diffrent types of array


In [87]:
#All 0s matrix
np.zeros((2, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [88]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [89]:
#any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [90]:
#Any other number(full_line)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [91]:
#Random decimal numbers
np.random.rand(4,2, 3)

array([[[0.85012185, 0.2560652 , 0.89328967],
        [0.99155713, 0.87714692, 0.78455728]],

       [[0.4617585 , 0.72048232, 0.39703528],
        [0.87452768, 0.84827175, 0.95978418]],

       [[0.65711799, 0.0887587 , 0.38224178],
        [0.85073095, 0.73849828, 0.43890076]],

       [[0.78457002, 0.60974737, 0.73773907],
        [0.56463128, 0.02117796, 0.10295189]]])

In [92]:
np.random.random_sample(a.shape)

array([[0.92879413, 0.72810525, 0.12473902, 0.59350934, 0.18102599,
        0.80119986, 0.8635325 ],
       [0.14011606, 0.90738761, 0.28741836, 0.01253142, 0.10730284,
        0.12140819, 0.61299155]])

In [94]:
#Random Integer values
np.random.randint(7, size = (3, 3))

array([[3, 4, 2],
       [4, 5, 0],
       [1, 1, 5]])

In [102]:
np.random.randint(-4,8, size = (4, 4))

array([[ 0,  1,  4, -3],
       [ 6,  5,  7,  4],
       [ 6,  4, -3,  6],
       [ 7,  2,  6,  0]])

In [103]:
#The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [113]:
#repeating an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [122]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
print(z)
z[1,1] = 9

output[1:-1, 1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful when copying arrays!!!


In [129]:
a = np.array([1,2, 3])
b = a.copy()
b[0] = 100

print(b)
print(a)

[100   2   3]
[1 2 3]


In [130]:
a = np.array([1,2 ,3, 4])
print(a)

[1 2 3 4]


In [131]:
a + 2

array([3, 4, 5, 6])

In [132]:
a -2

array([-1,  0,  1,  2])

In [133]:
a * 2

array([2, 4, 6, 8])

In [134]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [135]:
b = np.array([1, 0, 1, 0])
a + b

array([2, 2, 4, 4])

In [136]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [138]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [139]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

#### Linear Algebra

In [142]:
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [144]:
# Find the determinant

c = np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

In [147]:
## Refrence docs https://numpy.org/doc/stable/reference/routines.linalg.html

### Statistics with numpy

In [148]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [156]:
np.min(stats, axis = 1)

array([1, 4])

In [159]:
    np.max(stats, axis = 0)

array([4, 5, 6])

In [161]:
np.sum(stats, axis = 0)

array([5, 7, 9])

### Reorganizing Arrays

In [166]:
before = np.array([[1, 2,3,4], [5, 6, 7, 8]])
print(before)

after = before.reshape(2,2,2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [169]:
## Vertically stacking vectors
v1 = np.array([1,2 ,3,4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2])
np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [171]:
## Horizontal Stack
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

#### Miscellaneous

### Load data from file

In [176]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata.astype('int32')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

### Boolean Masking and Advanced Indxing

In [177]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [178]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [181]:
## You can index with a list in Numpy
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

a[[1,2 ,8]]

array([2, 3, 9])

In [184]:
np.any(filedata > 50 , axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [185]:
np.all(filedata > 50, axis = 0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [188]:
np.any(filedata > 50, axis = 1)

array([ True,  True,  True])

In [191]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [192]:
## Question answer
#question 1
a[2:4, 0:2]

IndexError: too many indices for array

In [ ]:
#question 2
a[[0, 1, 2, 3], [1, 2,3,4]]

In [193]:
#question 3
a[[0, 4,5], [3, 4]]

IndexError: too many indices for array